/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.stip.android.activity;

public final class R {
    public static final class anim {
        public static final int cycle_7=0x7f040000;
        public static final int fade=0x7f040001;
        public static final int hold=0x7f040002;
        public static final int hyperspace_in=0x7f040003;
        public static final int hyperspace_out=0x7f040004;
        public static final int layout_animation_row_left_slide=0x7f040005;
        public static final int layout_animation_row_right_slide=0x7f040006;
        public static final int layout_animation_table=0x7f040007;
        public static final int layout_bottom_to_top_slide=0x7f040008;
        public static final int layout_grid_fade=0x7f040009;
        public static final int layout_grid_inverse_fade=0x7f04000a;
        public static final int layout_random_fade=0x7f04000b;
        public static final int layout_wave_scale=0x7f04000c;
        public static final int push_left_in=0x7f04000d;
        public static final int push_left_out=0x7f04000e;
        public static final int push_right_in=0x7f04000f;
        public static final int push_right_out=0x7f040010;
        public static final int push_up_in=0x7f040011;
        public static final int push_up_out=0x7f040012;
        public static final int shake=0x7f040013;
        public static final int slide_left=0x7f040014;
        public static final int slide_right=0x7f040015;
        public static final int slide_top_to_bottom=0x7f040016;
        public static final int wave_scale=0x7f040017;
        public static final int zoom_enter=0x7f040018;
        public static final int zoom_exit=0x7f040019;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int code_ui=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int ic_pulltorefresh_arrow=0x7f020002;
        public static final int pull_to_refresh_header_background=0x7f020003;
        public static final int tile_bg=0x7f020004;
    }
    public static final class id {
        public static final int RelativeLayout01=0x7f06003d;
        public static final int RelativeLayout02=0x7f060053;
        public static final int RelativeLayout1=0x7f06007f;
        public static final int TextView01=0x7f060051;
        public static final int TextView02=0x7f060050;
        public static final int TextView03=0x7f060052;
        public static final int TextView04=0x7f06004f;
        public static final int TextView05=0x7f060056;
        public static final int TextView06=0x7f060055;
        public static final int TextView07=0x7f060057;
        public static final int TextView08=0x7f060054;
        public static final int ViewFlipper1=0x7f060032;
        public static final int act_abstracts=0x7f06000b;
        public static final int act_date=0x7f060004;
        public static final int act_email=0x7f060008;
        public static final int act_location=0x7f060005;
        public static final int act_name=0x7f060003;
        public static final int act_ok=0x7f06000c;
        public static final int act_org=0x7f060007;
        public static final int act_panel1=0x7f060001;
        public static final int act_photo=0x7f060002;
        public static final int act_qq=0x7f060009;
        public static final int act_val=0x7f06000a;
        public static final int activitylocation=0x7f060010;
        public static final int activityname=0x7f06000e;
        public static final int activitytime=0x7f06000f;
        public static final int buttonInsertUserInfo=0x7f060030;
        public static final int complete_dorm=0x7f06001c;
        public static final int complete_email=0x7f060016;
        public static final int complete_main_panel=0x7f060012;
        public static final int complete_ok_button=0x7f06001d;
        public static final int complete_phone=0x7f060018;
        public static final int complete_qq=0x7f060014;
        public static final int complete_shuoshuo=0x7f06001a;
        public static final int completeinfo_back=0x7f060011;
        public static final int editText1=0x7f06003f;
        public static final int editText2=0x7f060040;
        public static final int editText3=0x7f060041;
        public static final int ensure_back=0x7f06001f;
        public static final int ensure_button=0x7f060027;
        public static final int ensure_info_panel=0x7f060021;
        public static final int ensure_label_class=0x7f060026;
        public static final int ensure_label_department=0x7f060024;
        public static final int ensure_label_major=0x7f060025;
        public static final int ensure_label_name=0x7f060023;
        public static final int ensure_label_uid=0x7f060022;
        public static final int ensure_next=0x7f060020;
        public static final int linearLayout1=0x7f060065;
        public static final int login_autologin_checkbox=0x7f06002d;
        public static final int login_back=0x7f06002e;
        public static final int login_login_button=0x7f06002f;
        public static final int login_panel=0x7f060028;
        public static final int login_password_edit=0x7f06002b;
        public static final int login_password_label=0x7f06002a;
        public static final int login_uid_edit=0x7f06002c;
        public static final int login_uid_label=0x7f060029;
        public static final int new_page_panel=0x7f060034;
        public static final int newpage1=0x7f060033;
        public static final int newpage1_edit1=0x7f060035;
        public static final int newpage2=0x7f06003c;
        public static final int newpage_editText2=0x7f060037;
        public static final int newpage_editText3=0x7f060038;
        public static final int newpage_editText4=0x7f060039;
        public static final int newpage_textView2=0x7f060036;
        public static final int newspage_editText5=0x7f06003a;
        public static final int org_1=0x7f060043;
        public static final int org_2=0x7f060048;
        public static final int org_3=0x7f060045;
        public static final int org_4=0x7f060047;
        public static final int org_5=0x7f060046;
        public static final int org_6=0x7f060044;
        public static final int org_7=0x7f060049;
        public static final int org_panel=0x7f060042;
        public static final int org_right=0x7f060058;
        public static final int org_vf_1=0x7f06004a;
        public static final int password_back=0x7f060059;
        public static final int password_button_label=0x7f060061;
        public static final int password_edit_fisr=0x7f06005e;
        public static final int password_edit_second=0x7f06005f;
        public static final int password_label_first=0x7f06005c;
        public static final int password_label_second=0x7f06005d;
        public static final int password_next=0x7f06005a;
        public static final int password_ok_button=0x7f060060;
        public static final int password_setting_panel=0x7f06005b;
        public static final int personalinfo_lable_Email=0x7f06006b;
        public static final int personalinfo_lable_QQ=0x7f06006a;
        public static final int personalinfo_lable_dorm=0x7f06006c;
        public static final int personalinfo_lable_name=0x7f060064;
        public static final int personalinfo_lable_phone=0x7f060069;
        public static final int personalinfo_lable_scool=0x7f060067;
        public static final int personalinfo_lable_shuoshuo=0x7f06006d;
        public static final int personalinfo_lable_uid=0x7f060066;
        public static final int personalinfo_penel1=0x7f060062;
        public static final int personalinfo_pennel_2=0x7f060068;
        public static final int personalinfo_photo=0x7f060063;
        public static final int pullToRefreshListView1=0x7f060000;
        public static final int pull_to_refresh_header=0x7f06006e;
        public static final int pull_to_refresh_image=0x7f060070;
        public static final int pull_to_refresh_progress=0x7f06006f;
        public static final int pull_to_refresh_text=0x7f060071;
        public static final int pull_to_refresh_updated_at=0x7f060072;
        public static final int relativeLayout1=0x7f060031;
        public static final int relativeLayout2=0x7f060006;
        public static final int relativeLayout5=0x7f06003b;
        public static final int send_eidt=0x7f060075;
        public static final int send_label=0x7f060074;
        public static final int send_panel=0x7f060073;
        public static final int spinner1=0x7f06003e;
        public static final int textView1=0x7f06001e;
        public static final int textView2=0x7f060013;
        public static final int textView3=0x7f060015;
        public static final int textView4=0x7f060017;
        public static final int textView5=0x7f060019;
        public static final int textView6=0x7f06001b;
        public static final int textView9=0x7f06000d;
        public static final int usermain_activties=0x7f06007a;
        public static final int usermain_hot=0x7f060079;
        public static final int usermain_info=0x7f060077;
        public static final int usermain_left_panel=0x7f060076;
        public static final int usermain_news=0x7f060078;
        public static final int usermain_scan=0x7f06007c;
        public static final int usermain_schuele_date=0x7f06004b;
        public static final int usermain_schuele_location=0x7f06004e;
        public static final int usermain_schuele_name=0x7f06004c;
        public static final int usermain_schuele_time=0x7f06004d;
        public static final int usermain_setting=0x7f06007b;
        public static final int usermain_shcedule=0x7f06007d;
        public static final int viewFlipper1=0x7f06007e;
        public static final int welcome_login=0x7f060086;
        public static final int welcome_logo1=0x7f060084;
        public static final int welcome_logo_2=0x7f060085;
        public static final int welcome_logo_flipper=0x7f060083;
        public static final int welcome_name=0x7f060080;
        public static final int welcome_name_eidt=0x7f060082;
        public static final int welcome_next=0x7f060087;
        public static final int welcome_uid_eidt=0x7f060081;
    }
    public static final class layout {
        public static final int acititieslist=0x7f030000;
        public static final int activity=0x7f030001;
        public static final int activityitem=0x7f030002;
        public static final int completeinfo=0x7f030003;
        public static final int ensureinfo=0x7f030004;
        public static final int login=0x7f030005;
        public static final int main=0x7f030006;
        public static final int messages=0x7f030007;
        public static final int newactivty=0x7f030008;
        public static final int orgmain=0x7f030009;
        public static final int passwordsetting=0x7f03000a;
        public static final int personalinfo=0x7f03000b;
        public static final int pull_to_refresh=0x7f03000c;
        public static final int pull_to_refresh_header=0x7f03000d;
        public static final int sendmessage=0x7f03000e;
        public static final int usermain=0x7f03000f;
        public static final int welcome=0x7f030010;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
        public static final int pull_to_refresh_pull_label=0x7f050002;
        public static final int pull_to_refresh_refreshing_label=0x7f050004;
        public static final int pull_to_refresh_release_label=0x7f050003;
        public static final int pull_to_refresh_tap_label=0x7f050005;
    }
}
